language: python
sudo: false
python: 2.7
addons:
    apt:
        packages:
            - libev-dev
            - libevent-dev
install:
    - python setup.py develop
    - pip install tox
script: tox
notifications:
    email: tarek@mozilla.com
    irc: "irc.freenode.org#mozilla-circus"
    on_success: change
